Added possibility to load ports and steps in a different workflow
alpha-unito/streamflow pull request #274
Opened 2023-11-08 11:20 UTC by LanderOtto

This PR adds the possibility to load from the database the step and port instances in a different workflow. It can be helpful for future feature implementations, for example, fault tolerance, or resume a stopped workflow.
Furthermore, a bug in the loading of the Config class has been fixed.

Unit tests have been added for this new feature.

2023-12-01 00:51 UTC, LanderOtto commented
The PR is still WIP. Don't merge.

2024-01-07 16:37 UTC, GlassOfWhiskey requested changes

2024-01-07 16:37 UTC, GlassOfWhiskey commented on docs/source/ext/database.rst
> +Furthermore, it is in charge of assign the ``persistent_id`` when an entity is added in the cache with the ``add_deployment``, ``add_filter``, ``add_port``, ``add_step``, ``add_target``, ``add_token`
```suggestion
Furthermore, it is in charge of assign the ``persistent_id`` when an entity is added to the cache with the ``add_*`` methods.
```

2024-01-07 16:37 UTC, GlassOfWhiskey commented on docs/source/ext/database.rst
> +The ``WorkflowLoader`` allows the loading of the steps and ports of a workflow in a new one.
```suggestion
The ``WorkflowLoader`` class loads the steps and ports of an existing workflow from the database and inserts them into a new workflow object, which is passed as argument to the constructor.
```

2024-01-07 16:37 UTC, GlassOfWhiskey commented on docs/source/ext/database.rst
> +This feature can be helpful for the Fault Tolerance and the Resume features (see :ref:`Fault Tolerance <Fault tolerance>`).
Remove this sentence for now, as these features are not implemented yet

2024-01-07 16:37 UTC, GlassOfWhiskey commented on docs/source/ext/database.rst
> +The ``WorkflowLoader`` extends the ``DefaultDatabaseLoadingContext`` class and overrides only the methods involving the ``step``, ``port`` and ``workflow`` entities.
```suggestion
The ``WorkflowLoader`` class extends the ``DefaultDatabaseLoadingContext`` class and overrides the methods involving ``step``, ``port``, and ``workflow`` entities.
```

2024-01-13 12:03 UTC, GlassOfWhiskey requested changes

2024-01-13 12:03 UTC, GlassOfWhiskey commented on docs/source/ext/database.rst
> +.. code-block:: python
This code block can be removed, as the behaviour is clear from the previous description

2024-01-13 13:04 UTC, GlassOfWhiskey approved these changes

2024-01-13 13:06 UTC, merged