Improved gather
alpha-unito/streamflow pull request #348
Opened 2024-01-14 09:00 UTC by LanderOtto

This commit improves the performance of `GatherStep` with the additional information of the size of how many elements it has to wait before collecting them.
Before this commit, the `GatherStep` waited for the `TerminationToken` before collecting all the elements.

2024-01-14 10:47 UTC, GlassOfWhiskey requested changes

2024-01-14 10:47 UTC, GlassOfWhiskey commented on streamflow/cwl/transformer.py
> +                f"Values must be an positive integer. Got {next(iter(values))}"
```suggestion
                f"Values must be positive integers. Got {next(iter(values))}"
```

2024-01-14 10:47 UTC, GlassOfWhiskey commented on streamflow/cwl/transformer.py
> +            raise WorkflowExecutionException(f"Values must be equals. Got {values}")
```suggestion
            raise WorkflowExecutionException(f"Values must be equal. Got {values}")
```

2024-01-14 10:47 UTC, GlassOfWhiskey commented on streamflow/cwl/transformer.py
> +                    f"Values must be an positive integer. Got {token.value}"
```suggestion
                    f"Values must be positive integers. Got {token.value}"
```

2024-01-14 18:04 UTC, GlassOfWhiskey requested changes

2024-01-14 18:04 UTC, GlassOfWhiskey commented on streamflow/cwl/transformer.py
> +            self.get_output_name(): ListToken(
This part is quite strange:
- Why you clone only `ListToken` objects?
- Why you retag the List elements but not the `ListToken` itself?
- This is not actually cloning a `Token` instance, but it is creating a list of cloned tokens, which is something very strange

2024-01-16 09:00 UTC, GlassOfWhiskey requested changes

2024-01-16 09:00 UTC, GlassOfWhiskey commented on streamflow/cwl/transformer.py
> +        token = inputs[self.get_input_port_name()]
```suggestion
        input_token = inputs[self.get_input_port_name()]
        size_token = inputs["__size__"]
```

2024-01-16 09:00 UTC, GlassOfWhiskey commented on streamflow/cwl/transformer.py
> +        if not isinstance(next(iter(values)), int) or next(iter(values)) < 0:
```suggestion
        value = next(iter(values))
        if not isinstance(value, int) or value < 0:
```

2024-01-16 09:00 UTC, GlassOfWhiskey commented on streamflow/cwl/translator.py
> +            scatter_transformer = None
```suggestion
            scatter_size_transformer = None
```

2024-01-16 09:00 UTC, GlassOfWhiskey commented on streamflow/cwl/translator.py
> +                    scatter_transformer.add_output_port("__size__", size_port)
If size transformers do just this, move creation of `__size__` port directly in the constructor

2024-01-16 11:31 UTC, GlassOfWhiskey requested changes

2024-01-16 11:31 UTC, GlassOfWhiskey commented on streamflow/cwl/transformer.py
> +                f"Step {self.name} received {inputs['__size__'].tag} on size port and {input_token.tag} on {self.get_input_port_name()} port"
```suggestion
                f"Step {self.name} received {size_token.tag} on size port and {input_token.tag} on {self.get_input_port_name()} port"
```

2024-01-18 15:17 UTC, GlassOfWhiskey requested changes

2024-01-18 15:17 UTC, GlassOfWhiskey commented on streamflow/cwl/transformer.py
> +                f"Step {self.name} received {size_token.value} in the size port, but it must be a positive integer"
```suggestion
                f"Step {self.name} received {size_token.value} on replicas port, but it must be a positive integer"
```

2024-01-18 15:17 UTC, GlassOfWhiskey commented on streamflow/cwl/transformer.py
> +                f"Step {self.name} received {size_token.tag} on size port and {input_token.tag} on {self.get_input_port_name()} port"
```suggestion
                f"Step {self.name} received {size_token.tag} on replicas port and {input_token.tag} on {self.get_input_port_name()} port"
```

2024-01-18 15:17 UTC, GlassOfWhiskey commented on streamflow/cwl/transformer.py
> +                f"Step {self.name} received {values}, but they must be equal"
```suggestion
                f"Step {self.name} received {values}, but all sizes must be equal"
```

2024-01-18 15:36 UTC, LanderOtto commented
The CWL standard allows the execution of multiple instances of a step with different inputs; it is done using the `scatter` feature ([doc](https://www.commonwl.org/v1.0/Workflow.html#Scatter/gather)).
The `scatter` takes one or more lists and assigns the elements to multiple instances.

When there are two or more scatter inputs, combining them in different ways is possible.
There are three types of scatter methods: `dotproduct`, `flat_crossproduct` and `nested_crossproduct`.
With the scatter method, the number of inputs involved in the scatter, and how many elements have each input, it is possible to know how many elements we will have in the output.

# Current scatter implementation in StreamFlow
In StreamFlow, the scatter feature has three essential steps: `ScatterStep,` `CombinatorStep`, and `GatherStep.`
The number of these steps can change based on how many inputs are involved in the `scatter` and which method is used. 
In the base case with one scatter input, there are a single `ScatterStep` and a single `GatherStep`. 
With two or more scatter inputs, there are a `CombinatorStep`, one `ScatterStep` for each scatter input, and one `GatherStep` in the case of `dot_product` and `flat_crossproduct`, otherwise one `GatherStep` for each scatter input.

# Changes
We introduce in the `ScatterStep` a new output port called `__size__` where are put tokens with:
- value: the number of the elements in the scatter input list 
- tag: the same input tags.

Furthermore, we introduce a new input port in the `GatherStep` called `__size__` and add a new attribute called `self.size_map`. This attribute maps the tags with the number of elements expected.



## Single scatter input
In the case of a scatter on a single list in input, the `__size__` port of the `ScatterStep` is connected to the `__size__` port of the 'GatherStep'.

## Multiple scatter inputs
### Dot product
In the case of `dot_product`, the scatter input lists must have the same lenght and in output the `scatter` gives a list with the same length.
We introduce a new class, called `DotProductSizeTransformer`, which extends the `ManyToOneTransformer` class. 
The `DotProductSizeTransformer` input ports are all the `__size__` port of the `ScatterStep` involved, and its output port is connected to the `__size__` port of the `GatherStep`.
It checks that all the input tokens have the same value and then puts a new token with that value in the output port and the same input tags.

### Flat crossproduct
This scatter method combines all the elements of the lists with the elements of the other lists.
The number of all the possible combinations is the product of the list lengths and the output; we will have a single list.
We introduce a new class, called `CartesianProductSizeTransformer`, it is very similar to the `DotProductSizeTransformer` class. The difference is that it does check that the inputs have the same values. Moreover, it puts in output a token with the _product_ of the values and the same inputs tag.


### Nested crossproduct
Last but not least, the more complex case.
It is similar to the flas crossproduct, but in output it has a list of nested lists instead of a single (flattered) list.




WIP

2024-01-19 18:39 UTC, merged